### ISSUE TITLE
CSS recipe for wiki - heading numbers

### ISSUE THREAD

**Issue by will-hart** [RelaxedJS/ReLaXed#76]
What about another [CSS recipe for the wiki](https://github.com/RelaxedJS/ReLaXed/wiki/CSS-Recipes)? Something like:

---

### Numbered headings

If you want your headings automatically numbered by CSS, you can use the approach described in this  [Phil Archer blog post](https://philarcher.org/diary/2013/headingnumbers/). The following example numbers headings 2 and 3, but doesn't number `h1` tags or anything with the class `.nocount`. 

In your styles.scss, 

```css
body {counter-reset: h2}
h2 {counter-reset: h3}

h2:before {counter-increment: h2; content: counter(h2) ". "}
h3:before {counter-increment: h3; content: counter(h2) "." counter(h3) ". "}

h2.nocount:before, h3.nocount:before { content: ""; counter-increment: none }
```

---

**SOURCE**

```
### Numbered headings

If you want your headings automatically numbered by CSS, you can use the approach described in this [Phil Archer blog post](https://philarcher.org/diary/2013/headingnumbers/). The following example numbers headings 2 and 3, but doesn't number `h1` tags or anything with the class `.nocount`. 

In your styles.scss, 

    ```css
    body {counter-reset: h2}
    h2 {counter-reset: h3}

    h2:before {counter-increment: h2; content: counter(h2) ". "}
    h3:before {counter-increment: h3; content: counter(h2) "." counter(h3) ". "}

    h2.nocount:before, h3.nocount:before { content: ""; counter-increment: none }
    ```
```
